- name: Setup automatic content node upgrade cron job
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    base_path: "/home/ubuntu/node-operator-tooling"
    application_path: "/home/ubuntu/node-operator-tooling/content-node/docker-compose"
    git_repo_url: "https://github.com/earthfast/node-operator-tooling"
    cron_schedule: "0 */4 * * *"
    log_dir: "/var/log/earthfast"
    auto_upgrade_script: "{{ application_path }}/auto-upgrade.sh"

  tasks:
    - name: Ensure log directory exists
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    # Initial clone if repository doesn't exist
    - name: Check if repository exists
      stat:
        path: "{{ base_path }}/.git"
      register: repo_exists

    - name: Clone repository if needed
      become_user: ubuntu
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ base_path }}"
        force: yes
        version: main
      when: not repo_exists.stat.exists

    - name: Ensure auto-upgrade script is executable
      file:
        path: "{{ auto_upgrade_script }}"
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Setup cron job
      cron:
        name: "Git auto-upgrade"
        job: "{{ auto_upgrade_script }}"
        user: ubuntu
        minute: "{{ cron_schedule.split(' ')[0] }}"
        hour: "{{ cron_schedule.split(' ')[1] }}"
        day: "{{ cron_schedule.split(' ')[2] }}"
        month: "{{ cron_schedule.split(' ')[3] }}"
        weekday: "{{ cron_schedule.split(' ')[4] }}"

    - name: Configure logrotate
      copy:
        dest: /etc/logrotate.d/git-auto-upgrade
        mode: '0644'
        content: |
          {{ log_dir }}/git-auto-upgrade.log {
            rotate 7
            daily
            compress
            missingok
            notifempty
            create 0644 ubuntu ubuntu
          }
